-- `node-data`.circuits definition

CREATE TABLE `circuits` (
  `canonical_key` varchar(100) NOT NULL,
  `endpoint1` varchar(50) NOT NULL,
  `endpoint2` varchar(50) NOT NULL,
  `status` enum('Active','Disconnected') NOT NULL DEFAULT 'Active',
  `connected_at` datetime(6) DEFAULT NULL,
  `disconnected_at` datetime(6) DEFAULT NULL,
  `last_update` datetime(6) NOT NULL,
  `initiator` varchar(50) DEFAULT NULL,
  `ep1_node` varchar(20) DEFAULT NULL,
  `ep1_circuit_id` int(11) DEFAULT NULL,
  `ep1_direction` varchar(10) DEFAULT NULL,
  `ep1_service` int(11) DEFAULT NULL,
  `ep1_remote` varchar(50) DEFAULT NULL,
  `ep1_local` varchar(50) DEFAULT NULL,
  `ep1_segments_sent` int(11) DEFAULT NULL,
  `ep1_segments_received` int(11) DEFAULT NULL,
  `ep1_segments_resent` int(11) DEFAULT NULL,
  `ep1_segments_queued` int(11) DEFAULT NULL,
  `ep1_bytes_sent` bigint(20) DEFAULT NULL,
  `ep1_bytes_received` bigint(20) DEFAULT NULL,
  `ep1_last_update` datetime(6) DEFAULT NULL,
  `ep2_node` varchar(20) DEFAULT NULL,
  `ep2_circuit_id` int(11) DEFAULT NULL,
  `ep2_direction` varchar(10) DEFAULT NULL,
  `ep2_service` int(11) DEFAULT NULL,
  `ep2_remote` varchar(50) DEFAULT NULL,
  `ep2_local` varchar(50) DEFAULT NULL,
  `ep2_segments_sent` int(11) DEFAULT NULL,
  `ep2_segments_received` int(11) DEFAULT NULL,
  `ep2_segments_resent` int(11) DEFAULT NULL,
  `ep2_segments_queued` int(11) DEFAULT NULL,
  `ep2_bytes_sent` bigint(20) DEFAULT NULL,
  `ep2_bytes_received` bigint(20) DEFAULT NULL,
  `ep2_last_update` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`canonical_key`),
  KEY `idx_endpoint1` (`endpoint1`),
  KEY `idx_endpoint2` (`endpoint2`),
  KEY `idx_status` (`status`),
  KEY `idx_last_update` (`last_update`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;