-- `node-data`.links definition

CREATE TABLE `links` (
  `canonical_key` varchar(50) NOT NULL,
  `endpoint1` varchar(20) NOT NULL,
  `endpoint2` varchar(20) NOT NULL,
  `status` enum('Active','Disconnected') NOT NULL DEFAULT 'Active',
  `connected_at` datetime(6) DEFAULT NULL,
  `disconnected_at` datetime(6) DEFAULT NULL,
  `last_update` datetime(6) NOT NULL,
  `initiator` varchar(20) DEFAULT NULL,
  `is_rf` tinyint(1) DEFAULT NULL COMMENT 'Whether this link uses RF (true), internet (false), or unknown (NULL)',
  `flap_count` int(11) NOT NULL DEFAULT 0 COMMENT 'Number of up/down transitions within the current flap detection window',
  `flap_window_start` datetime(6) DEFAULT NULL COMMENT 'Start time of the current flap detection window',
  `last_flap_time` datetime(6) DEFAULT NULL COMMENT 'Timestamp of the most recent flap (up/down transition)',
  `ep1_node` varchar(20) DEFAULT NULL,
  `ep1_link_id` int(11) DEFAULT NULL,
  `ep1_direction` varchar(10) DEFAULT NULL,
  `ep1_port` varchar(20) DEFAULT NULL,
  `ep1_remote` varchar(20) DEFAULT NULL,
  `ep1_local` varchar(20) DEFAULT NULL,
  `ep1_frames_sent` int(11) DEFAULT NULL,
  `ep1_frames_received` int(11) DEFAULT NULL,
  `ep1_frames_resent` int(11) DEFAULT NULL,
  `ep1_frames_queued` int(11) DEFAULT NULL,
  `ep1_frames_queued_peak` int(11) DEFAULT NULL,
  `ep1_bytes_sent` bigint(20) DEFAULT NULL,
  `ep1_bytes_received` bigint(20) DEFAULT NULL,
  `ep1_bps_tx_mean` int(11) DEFAULT NULL,
  `ep1_bps_rx_mean` int(11) DEFAULT NULL,
  `ep1_frame_queue_max` int(11) DEFAULT NULL,
  `ep1_l2_rtt_ms` int(11) DEFAULT NULL,
  `ep1_up_for_secs` int(11) DEFAULT NULL,
  `ep1_last_update` datetime(6) DEFAULT NULL,
  `ep2_node` varchar(20) DEFAULT NULL,
  `ep2_link_id` int(11) DEFAULT NULL,
  `ep2_direction` varchar(10) DEFAULT NULL,
  `ep2_port` varchar(20) DEFAULT NULL,
  `ep2_remote` varchar(20) DEFAULT NULL,
  `ep2_local` varchar(20) DEFAULT NULL,
  `ep2_frames_sent` int(11) DEFAULT NULL,
  `ep2_frames_received` int(11) DEFAULT NULL,
  `ep2_frames_resent` int(11) DEFAULT NULL,
  `ep2_frames_queued` int(11) DEFAULT NULL,
  `ep2_frames_queued_peak` int(11) DEFAULT NULL,
  `ep2_bytes_sent` bigint(20) DEFAULT NULL,
  `ep2_bytes_received` bigint(20) DEFAULT NULL,
  `ep2_bps_tx_mean` int(11) DEFAULT NULL,
  `ep2_bps_rx_mean` int(11) DEFAULT NULL,
  `ep2_frame_queue_max` int(11) DEFAULT NULL,
  `ep2_l2_rtt_ms` int(11) DEFAULT NULL,
  `ep2_up_for_secs` int(11) DEFAULT NULL,
  `ep2_last_update` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`canonical_key`),
  KEY `idx_endpoint1` (`endpoint1`),
  KEY `idx_endpoint2` (`endpoint2`),
  KEY `idx_status` (`status`),
  KEY `idx_last_update` (`last_update`),
  KEY `idx_is_rf` (`is_rf`),
  KEY `idx_flap_count` (`flap_count`),
  KEY `idx_last_flap_time` (`last_flap_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;