-- `node-data`.nodes definition

CREATE TABLE `nodes` (
  `callsign` varchar(20) NOT NULL,
  `alias` varchar(10) DEFAULT NULL,
  `locator` varchar(8) DEFAULT NULL,
  `latitude` decimal(10,6) DEFAULT NULL,
  `longitude` decimal(11,6) DEFAULT NULL,
  `software` varchar(50) DEFAULT NULL,
  `version` varchar(50) DEFAULT NULL,
  `uptime_secs` int(11) DEFAULT NULL,
  `links_in` int(11) DEFAULT NULL,
  `links_out` int(11) DEFAULT NULL,
  `circuits_in` int(11) DEFAULT NULL,
  `circuits_out` int(11) DEFAULT NULL,
  `l3_relayed` int(11) DEFAULT NULL,
  `status` enum('Unknown','Online','Offline') NOT NULL DEFAULT 'Unknown',
  `last_seen` datetime(6) DEFAULT NULL,
  `first_seen` datetime(6) DEFAULT NULL,
  `last_status_update` datetime(6) DEFAULT NULL,
  `last_up_event` datetime(6) DEFAULT NULL,
  `last_down_event` datetime(6) DEFAULT NULL,
  `l2_trace_count` int(11) NOT NULL DEFAULT 0,
  `last_l2_trace` datetime(6) DEFAULT NULL,
  `ip_address_obfuscated` varchar(45) DEFAULT NULL,
  `geoip_country_code` varchar(2) DEFAULT NULL,
  `geoip_country_name` varchar(100) DEFAULT NULL,
  `geoip_city` varchar(100) DEFAULT NULL,
  `last_ip_update` datetime DEFAULT NULL,
  `is_reporting_node` tinyint(1) NOT NULL DEFAULT 0,
  `is_cb` tinyint(1) NOT NULL DEFAULT 0,
  `is_test` tinyint(1) NOT NULL DEFAULT 0,
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`callsign`),
  KEY `idx_status` (`status`),
  KEY `idx_last_seen` (`last_seen`),
  KEY `idx_software` (`software`),
  KEY `idx_geoip_country` (`geoip_country_code`),
  KEY `idx_is_reporting_node` (`is_reporting_node`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;