-- Network State Schema
-- This schema maintains the current snapshot of the network state
-- All operations are designed to be idempotent for multi-instance deployments

-- Nodes table - stores current state of all nodes
CREATE TABLE IF NOT EXISTS `nodes` (
    `callsign` VARCHAR(20) NOT NULL PRIMARY KEY,
    `alias` VARCHAR(10) NULL,
    `locator` VARCHAR(8) NULL,
    `latitude` DECIMAL(10, 6) NULL,
    `longitude` DECIMAL(11, 6) NULL,
    `software` VARCHAR(50) NULL,
    `version` VARCHAR(20) NULL,
    `uptime_secs` INT NULL,
    `links_in` INT NULL,
    `links_out` INT NULL,
    `circuits_in` INT NULL,
    `circuits_out` INT NULL,
    `l3_relayed` INT NULL,
    `status` ENUM('Unknown', 'Up', 'Down') NOT NULL DEFAULT 'Unknown',
    `last_seen` DATETIME(6) NULL,
    `first_seen` DATETIME(6) NULL,
    `last_status_update` DATETIME(6) NULL,
    `last_up_event` DATETIME(6) NULL,
    `last_down_event` DATETIME(6) NULL,
    `l2_trace_count` INT NOT NULL DEFAULT 0,
    `last_l2_trace` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX `idx_status` (`status`),
    INDEX `idx_last_seen` (`last_seen`),
    INDEX `idx_software` (`software`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Links table - stores current state of all AX.25 links
CREATE TABLE IF NOT EXISTS `links` (
    `canonical_key` VARCHAR(50) NOT NULL PRIMARY KEY,
    `endpoint1` VARCHAR(20) NOT NULL,
    `endpoint2` VARCHAR(20) NOT NULL,
    `status` ENUM('Unknown', 'Connected', 'Disconnected') NOT NULL DEFAULT 'Unknown',
    `connected_at` DATETIME(6) NULL,
    `disconnected_at` DATETIME(6) NULL,
    `last_update` DATETIME(6) NOT NULL,
    `initiator` VARCHAR(20) NULL,
    -- Endpoint 1 state
    `ep1_node` VARCHAR(20) NULL,
    `ep1_link_id` INT NULL,
    `ep1_direction` VARCHAR(10) NULL,
    `ep1_port` VARCHAR(20) NULL,
    `ep1_remote` VARCHAR(20) NULL,
    `ep1_local` VARCHAR(20) NULL,
    `ep1_frames_sent` INT NULL,
    `ep1_frames_received` INT NULL,
    `ep1_frames_resent` INT NULL,
    `ep1_frames_queued` INT NULL,
    `ep1_frames_queued_peak` INT NULL,
    `ep1_bytes_sent` BIGINT NULL,
    `ep1_bytes_received` BIGINT NULL,
    `ep1_bps_tx_mean` INT NULL,
    `ep1_bps_rx_mean` INT NULL,
    `ep1_frame_queue_max` INT NULL,
    `ep1_l2_rtt_ms` INT NULL,
    `ep1_up_for_secs` INT NULL,
    `ep1_last_update` DATETIME(6) NULL,
    -- Endpoint 2 state
    `ep2_node` VARCHAR(20) NULL,
    `ep2_link_id` INT NULL,
    `ep2_direction` VARCHAR(10) NULL,
    `ep2_port` VARCHAR(20) NULL,
    `ep2_remote` VARCHAR(20) NULL,
    `ep2_local` VARCHAR(20) NULL,
    `ep2_frames_sent` INT NULL,
    `ep2_frames_received` INT NULL,
    `ep2_frames_resent` INT NULL,
    `ep2_frames_queued` INT NULL,
    `ep2_frames_queued_peak` INT NULL,
    `ep2_bytes_sent` BIGINT NULL,
    `ep2_bytes_received` BIGINT NULL,
    `ep2_bps_tx_mean` INT NULL,
    `ep2_bps_rx_mean` INT NULL,
    `ep2_frame_queue_max` INT NULL,
    `ep2_l2_rtt_ms` INT NULL,
    `ep2_up_for_secs` INT NULL,
    `ep2_last_update` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX `idx_endpoint1` (`endpoint1`),
    INDEX `idx_endpoint2` (`endpoint2`),
    INDEX `idx_status` (`status`),
    INDEX `idx_last_update` (`last_update`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Circuits table - stores current state of all NetROM Layer 4 circuits
CREATE TABLE IF NOT EXISTS `circuits` (
    `canonical_key` VARCHAR(100) NOT NULL PRIMARY KEY,
    `endpoint1` VARCHAR(50) NOT NULL,
    `endpoint2` VARCHAR(50) NOT NULL,
    `status` ENUM('Unknown', 'Connected', 'Disconnected') NOT NULL DEFAULT 'Unknown',
    `connected_at` DATETIME(6) NULL,
    `disconnected_at` DATETIME(6) NULL,
    `last_update` DATETIME(6) NOT NULL,
    `initiator` VARCHAR(50) NULL,
    -- Endpoint 1 state
    `ep1_node` VARCHAR(20) NULL,
    `ep1_circuit_id` INT NULL,
    `ep1_direction` VARCHAR(10) NULL,
    `ep1_service` INT NULL,
    `ep1_remote` VARCHAR(50) NULL,
    `ep1_local` VARCHAR(50) NULL,
    `ep1_segments_sent` INT NULL,
    `ep1_segments_received` INT NULL,
    `ep1_segments_resent` INT NULL,
    `ep1_segments_queued` INT NULL,
    `ep1_bytes_sent` BIGINT NULL,
    `ep1_bytes_received` BIGINT NULL,
    `ep1_last_update` DATETIME(6) NULL,
    -- Endpoint 2 state
    `ep2_node` VARCHAR(20) NULL,
    `ep2_circuit_id` INT NULL,
    `ep2_direction` VARCHAR(10) NULL,
    `ep2_service` INT NULL,
    `ep2_remote` VARCHAR(50) NULL,
    `ep2_local` VARCHAR(50) NULL,
    `ep2_segments_sent` INT NULL,
    `ep2_segments_received` INT NULL,
    `ep2_segments_resent` INT NULL,
    `ep2_segments_queued` INT NULL,
    `ep2_bytes_sent` BIGINT NULL,
    `ep2_bytes_received` BIGINT NULL,
    `ep2_last_update` DATETIME(6) NULL,
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX `idx_endpoint1` (`endpoint1`),
    INDEX `idx_endpoint2` (`endpoint2`),
    INDEX `idx_status` (`status`),
    INDEX `idx_last_update` (`last_update`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
