name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: m0lte/node-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test Tests/ --no-restore --configuration Release --logger "console;verbosity=minimal"

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        run: |
          cd node-api
          dotnet publish \
            --configuration Release \
            --runtime linux-x64 \
            --self-contained false \
            /t:PublishContainer \
            /p:ContainerRegistry=${{ env.REGISTRY }} \
            /p:ContainerRepository=${{ env.IMAGE_NAME }} \
            /p:ContainerImageTags="${{ steps.meta.outputs.tags }}"

      - name: Build Docker image (PR only - no push)
        if: github.event_name == 'pull_request'
        run: |
          cd node-api
          dotnet publish \
            --configuration Release \
            --runtime linux-x64 \
            --self-contained false \
            /t:PublishContainer

      - name: Image digest
        if: github.event_name != 'pull_request'
        run: echo "Image pushed with tags - ${{ steps.meta.outputs.tags }}"
